#!/bin/sh

CONDITION_NAME=supported_major_os_upgrades
DEFAULTS=/usr/bin/defaults
MUNKI_DIR=$($DEFAULTS read /Library/Preferences/ManagedInstalls ManagedInstallDir)
COND_DOMAIN="${MUNKI_DIR}/ConditionalItems"

$DEFAULTS write "${COND_DOMAIN}" "${CONDITION_NAME}" -array

# Lion will run if the CPU is 64-bit
sysctl -n hw.cpu64bit_capable | grep 1 > /dev/null
if [ $? -eq 0 ]; then
    $DEFAULTS write "${COND_DOMAIN}" "${CONDITION_NAME}" -array-add "10.7"
fi

# 64-bit EFI is currently enough to determine Mountain Lion / Mavericks compatibility
ioreg -l -p IODeviceTree | grep -E 'firmware-abi.*EFI64' > /dev/null
if [ $? -eq 0 ]; then
    $DEFAULTS write "${COND_DOMAIN}" "${CONDITION_NAME}" -array-add "10.8"
    $DEFAULTS write "${COND_DOMAIN}" "${CONDITION_NAME}" -array-add "10.9"
fi
